services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: "ach_db"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - ./db-init:/docker-entrypoint-initdb.d
            - pgdata:/var/lib/postgresql/data
    haskell-server:
        build: .
        depends_on:
          - db
        ports:
          - "8080:8080"
        environment:
          DATABASE_URL: postgres://postgres:postgres@db:5432/ach_db
        volumes:
          - .:/app
          - .:/src
volumes:
    pgdata:
