services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: "ach_db"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - ./db-init:/docker-entrypoint-initdb.d
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
